api_platform:
    title: 'Sporty API'
    description: 'Best API for soccer'
    version: '1.0'
    collection:
        pagination:
            enabled: true
    formats:
        json:
            mime_types: ['application/json']

        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
