register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

price:
    path:       /{_locale}/price
    controller: App\Controller\PriceController::index
    requirements:
        _locale: en|fr

account_login:
    path:       /{_locale}/login
    controller: App\Controller\AccountController::login
    requirements:
        _locale: en|fr

home:
    path:       /
    controller: App\Controller\HomeController::index
    requirements:
        _locale: en|fr

home_translate:
    path:       /{_locale}
    controller: App\Controller\HomeController::index
    requirements:
        _locale: en|fr